name: Debugger
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 21
    - uses: actions/setup-java@v3
      with:
       distribution: 'zulu' # Azul Zulu OpenJDK
       java-version: '21'
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        check-latest: true
    - name: Install Dependencies
      timeout-minutes: 40
      run: |
        rm -rf *.js *.md .git .github LICENSE .gitignore
        sudo cp ./.init/.tmate.conf ~/.tmate.conf
        sudo apt-get install -y htop git wget curl btop
        curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
        sudo apt-get install speedtest
        cat << EOF > ~/README
        您正在使用由 HackPig520 提供的免费 Linux 服务器，基于 Github Actions
        ---
        你可以创建、修改、删除文件，运行可执行文件或者使用各种 CLI 程序
        想要测试服务器网速？键入以下命令
         $ speedtest
        想要查看 IP 以及详细信息？键入以下命令
         $ curl cip.cc
        想要编译源代码？系统预装了 Java Python Golang 等语言工具，可开箱即用！
        想要持续连接服务器？创建空文件 '/tmp/hackpig520' 以禁用 5 分钟免费时长限制(最多 35 分钟)
        想要立即断开连接并保留您的工作，创建空文件 '/tmp/stop' 以立即断开连接并保留您的工作('~/data' 目录下的所有文件)
        警告：不要 挖矿/删库 否则我们会失去该服务器并封禁您的访问！
        ---
        Using it for harmful purposes is extremely forbidden, HackPig520 is not responsible for its’ usages and consequences. / 严禁将其用于有害目的，我们不对其使用和后果负责。
        EOF
        bash ./.init/script.sh
        exit 0
    - uses: actions/upload-artifact@v3
      with:
        name: work-artifact
        path: ~/data
        retention-days: 7
        if-no-files-found: warn
