name: Debugger
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-java@v3
      with:
       distribution: 'zulu' # Azul Zulu OpenJDK
       java-version: '17'
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.3'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        check-latest: true
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        # !!!!!!!!!!!!! Remember to update auth key 90 days later !!!!!!!!!!!!!
        authkey: ${{ secrets.TS_AUTHKEY }}
        # !!!!!!!!!!!!! Remember to update auth key 90 days later !!!!!!!!!!!!!
    - name: Install Dependencies
      timeout-minutes: 40
      run: |
        rm -rf *.js *.md .git .github LICENSE .gitignore
        sudo cp ./.init/.tmate.conf ~/.tmate.conf
        sudo apt-get install -y htop speedtest-cli git wget curl
        bash ./.init/script.sh
        exit 0
    - uses: actions/upload-artifact@v3
      with:
        name: work-artifact
        path: ~/work
        retention-days: 3
        if-no-files-found: warn
